name: markdown_editor
description: A new flutter package project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.2.0
  url_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - packages/markdown_editor/images/undo_img.png
    - packages/markdown_editor/images/redo_img.png
    - packages/markdown_editor/images/edit_img.png
    - packages/markdown_editor/images/link_img.png
    - packages/markdown_editor/images/format_bold_img.png
    - packages/markdown_editor/images/format_italic_img.png
    - packages/markdown_editor/images/strikethrough_img.png
    - packages/markdown_editor/images/format_quote_img.png
    - packages/markdown_editor/images/list_img.png
    - packages/markdown_editor/images/format_header_1_img.png
    - packages/markdown_editor/images/format_header_2_img.png
    - packages/markdown_editor/images/format_header_3_img.png
    - packages/markdown_editor/images/format_header_4_img.png
    - packages/markdown_editor/images/format_header_5_img.png

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: MyIconFont
      fonts:
        - asset: packages/markdown_editor/fonts/iconfont.ttf

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
